### PR TITLE
Add appinfo/ folder

### PR DESCRIPTION
**Pull request by LukasReschke**
All folders shipped in the "/apps/" folder by default need to have an appinfo folder to store the code signature for the integrity checker. This is regardless of the fact whether it's an ownCloud app or not.

@VicDeo @DeepDiver1975 @karlitschek Required for the release signing. Please review.

### CODE REVIEW

**Comment by VicDeo** [comment]
@LukasReschke this is NOT an Owncloud **app** any more 
It is located not in `apps` but in `updater` directory

**Comment by LukasReschke** [comment]
So within the root folder of ownCloud? That makes sense and would just require a change on the packaging script. Can you confirm?

**Comment by VicDeo** [comment]
@LukasReschke I'm not sure if it will be distributed with oc package.
@karlitschek Is there any decision on this point?

**Comment by karlitschek** [comment]
it will be shipped as part of the owncloud release in the root folder. no appinfo or seperate signing is needed

**Pull request closed without merging**
