### PR TITLE
[Stable9] Fallback to localhost and then to CLI, use --key=value notation for CLI

### LINKED ISSUE #383: escapeArgument in OccRunner.php breaks commandline flags
Hi,

I am running 9.0.4.1 on FreeBSD 10.3. When I issue (as my HTTP server user, using bash as my shell)

    $ php updater/application.php upgrade:start

I get
````
[Symfony\Component\Process\Exception\ProcessFailedException]                                                  
  The command "php /usr/local/www/owncloud/occ --no-warnings app:list --output=json '--shipped false'" failed.  
  Exit Code: 1(General error)                                                                                   
  Output:                                                                                                       
  ================                                                                                              
  Error Output:                                                                                                 
  ================                                                                                              
                                                                                                                
    [Symfony\Component\Console\Exception\RuntimeException]                                                      
    The "--shipped false" option does not exist.                                                                
                                                                                                                
  app:list [--output [OUTPUT]] [--shipped SHIPPED]
````

The problem is caused by false escaping of the commandline parameters:

    php /usr/local/www/owncloud/occ --no-warnings app:list --output=json '--shipped false'

does raise the above exception, while

    php /usr/local/www/owncloud/occ --no-warnings app:list --output=json --shipped false

(note the missing quotes around the --shipped flag) works as expected.

IMHO, this is caused by using ProcessUtils::escapeArguments($line) in [OccRunner.php line 62](https://github.com/owncloud/updater/blob/master/src/Utils/OccRunner.php#L62): If I use `$line` instead of `$escapedLine` when composing the `$cmdLine` variable, everything works as expected.

### PR DESCRIPTION
**Pull request by VicDeo**
Backport of https://github.com/owncloud/updater/pull/388 (fixes #383)
+
Fix for https://github.com/owncloud/updater/issues/378

### CODE REVIEW

**Comment by VicDeo** [comment]
@davitol @PVince I tried to make it as small as possible. 
Tested with docker instance 9.0.4->9.0.5 
works for me

**Comment by davitol** [comment]
:+1: WFM

**Comment by pvince** [comment]
Hey, I just wanted to chime in @VicDeo. I keep getting emails from the 'OwnCloud' project due to being mentioned in issues.  I believe you are trying to mention @PVince81, but you keep typing @PVince 

Each time you type @PVince I get an email linking me to the comment thread since it is a 'Mention'.  This also means that @PVince81 is not getting the alert.

Thanks!

**Comment by VicDeo** [comment]
Stable9.1: https://github.com/owncloud/updater/pull/398

**Pull request merged**
