### PR TITLE
update text on delay of availability

### LINKED ISSUE #183: Add note that updates to new versions are always delayed a little bit
As users expect that the updater serves updates ASAP which gives wrong impression and a lot of people complain always.

See http://www.heise.de/forum/Open-Source/News-Kommentare/Owncloud-8-2-mit-neuen-Features-fuer-User-und-Admins/Ich-glaube-das-wars-dann-fuer-mich/posting-23831453/show/  for some more details. Probably just adding a note  like "Major updates are delayed up to one month until they are served by the updater application." somewhere.

cc @jospoortvliet as discussed
@karlitschek thoughts?

### PR DESCRIPTION
**Pull request by jospoortvliet**
Note that it's about major releases and it can take up to a month.

Fixes #183

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by RealRancor** [comment]
As minor releases are also delayed for some days i would note both cases.

**Comment by jospoortvliet** [comment]
if that is, otherwise, a :+1: from @RealRancor I think this can be merged...

**Comment by jospoortvliet** [comment]
@VicDeo it is just a text change, shouldn't impact tests or anything. Could you merge?

**Comment by VicDeo** [comment]
@jospoortvliet OK, I should warn that this change will be overwritten once https://github.com/owncloud/updater/pull/187 is merged

**Comment by jospoortvliet** [comment]
ok, tnx for note.

**Pull request merged**
