### PR TITLE
Add CHANGELOG.md to whitelist

### LINKED ISSUE #436: Add CHANGELOG.md to files to update
Update from 10.0.2->10.0.3beta with the web updater using https://github.com/owncloud/administration/pull/137.

Expected: no integrity check errors
Actual: CHANGELOG.md is marked as missing file

@VicDeo please add it

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #436

### CODE REVIEW

**Comment by PVince81** [comment]
@VicDeo please backport to stable10

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/updater/pull/439

**Comment by VicDeo** [comment]
@PVince81 what about stable9.1?
This file is also missing when migrating from 9.1.6 to 10.0.3

**Comment by PVince81** [comment]
Ok, then add it there

**Pull request merged**
