### PR TITLE
Make rmdirr public

### LINKED ISSUE #336: Upgrade from 9.0 to 9.1 fails
### Steps to reproduce
1. Install daily stable9 tarball (9.0.1 (daily) Build:2016-04-26T03:20:01+00:00 6c861f71eb62e9cee2617a472bcd6d37bfd7b899)
2. Make sure the updater downloads the daily master package (*)
3. Run the updater

### Expected behaviour
Updater upgrades to 9.1

### Actual behaviour
Upgrade fails

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 9.1.0 pre alpha 2016-04-26T03:08:09+00:00 d8f327831e6f64658c50131c2e7344ee6fa0e86a

**Updated from an older ownCloud or fresh install:** updated from 9.0.1 daily

### Updater trace
```
ownCloud updater 1.0 - CLI based ownCloud server upgrades
Checking system health.
 - file permissions are ok.
Current version is 9.0.1.3
Online version is 100.0.0.0 [daily]
What would you do next?
  [0] download
  [1] upgrade
  [2] abort
 > 1
Downloaded 100% (35076540 of 35076540)
Created checkpoint 9.0.1.3-571f8686a86f2
 simulated (optionally, can be done online in advance)
real [danger, might take long]
Extracting source into /opt/owncloud/data/updater-data/_oc_upgrade/100.0.0.0
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)


Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Reset log level

Upgrading the application activity
PHP Fatal error:  Call to protected method Owncloud\Updater\Utils\FilesystemHelper::rmdirr() from context 'Owncloud\Updater\Command\UpgradeShippedAppsCommand' in /opt/owncloud/updater/src/Command/UpgradeShippedAppsCommand.php on line 75
```

### Update.log
```
[info] Execution of upgrade:start command started
[info] Execution of upgrade:info command started
[info] Execution of upgrade:info command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.0.1.3 found
[info] Execution of upgrade:detect command stopped. Exit code is 4
[info] Execution of upgrade:start command stopped. Exit code is 0
[info] Execution of upgrade:start command started
[info] Execution of upgrade:info command started
[info] Execution of upgrade:info command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.0.1.3 found
[info] Execution of upgrade:detect command stopped. Exit code is 128
[info] Execution of upgrade:start command stopped. Exit code is 0
[info] Execution of upgrade:start command started
[info] Execution of upgrade:info command started
[info] Execution of upgrade:info command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.0.1.3 found
[info] Execution of upgrade:detect command stopped. Exit code is 0
[info] Execution of upgrade:backupDb command started
[info] Execution of upgrade:backupDb command stopped. Exit code is 0
[info] Execution of upgrade:backupData command started
[info] Execution of upgrade:backupData command stopped. Exit code is 0
[info] Execution of upgrade:checkpoint command started
[info] Execution of upgrade:checkpoint command stopped. Exit code is 0
[info] Execution of upgrade:preUpgradeRepair command started
[info] Execution of upgrade:preUpgradeRepair command stopped. Exit code is 0
[info] Execution of upgrade:dbUpgrade command started
[info] Execution of upgrade:dbUpgrade command stopped. Exit code is 0
[info] Execution of upgrade:dbUpgrade command started
[info] Execution of upgrade:dbUpgrade command stopped. Exit code is 0
[info] Execution of upgrade:disableNotShippedApps command started
[info] Execution of upgrade:disableNotShippedApps command stopped. Exit code is 0
[info] Execution of upgrade:executeCoreUpgradeScripts command started
[debug] Replacing 3rdparty
[debug] Replacing config/config.sample.php
[debug] Replacing core
[debug] Replacing l10n
[debug] Replacing lib
[debug] Replacing ocs
[debug] Replacing ocs-provider
[debug] Replacing resources
[debug] Replacing settings
[debug] Replacing .htaccess
[debug] Replacing .mailmap
[debug] Replacing .tag
[debug] Replacing .user.ini
[debug] Replacing AUTHORS
[debug] Replacing console.php
[debug] Replacing COPYING-AGPL
[debug] Replacing cron.php
[debug] Replacing db_structure.xml
[debug] Replacing index.html
[debug] Replacing index.php
[debug] Replacing indie.json
[debug] Replacing occ
[debug] Replacing public.php
[debug] Replacing remote.php
[debug] Replacing robots.txt
[debug] Replacing status.php
[debug] Replacing version.php
[info] Execution of upgrade:executeCoreUpgradeScripts command stopped. Exit code is 0
[info] Execution of upgrade:upgradeShippedApps command started
```

(*) The url where the updater downloads the file changed to make sure the daily master package (9.1) is downloaded for the current version. In addition, the build date of the current version (9.0.1) was modified (it was set 2 days ago), probably needed for the server side.

Probably related to https://github.com/owncloud/updater/issues/335

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #336

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

@LukasReschke @DeepDiver1975 second review ?

**Comment by PVince81** [comment]
@karlitschek backport ?

**Comment by karlitschek** [comment]
makes sense. please backport :+1:

**Comment by PVince81** [comment]
@VicDeo when you do backports or PRs, it is best if you could add a comment so we get a notification when it's done. Thanks

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/updater/issues/338

**Pull request merged**
