### PR TITLE
Move extractionBaseDir under the data/updater

### PR DESCRIPTION
**Pull request by VicDeo**

### CODE REVIEW

**Comment by VicDeo** [comment]
Fixes #318

**Comment by PVince81** [comment]
Code looks good :+1: 

@LukasReschke please review

**Comment by PVince81** [comment]
@karlitschek backport to 9.0.2 ?

**Comment by karlitschek** [comment]
backport is ok :+1:

**Comment by VicDeo** [comment]
Stable9: https://github.com/owncloud/updater/issues/327

**Pull request merged**
