### PR TITLE
Pass parameters that we started to inject in master. Fixes #66

### LINKED ISSUE #66: Problem in OC 8 alpha 1
When I try to open the updater app, I get:

> Fatal error: Call to a member function getValue() on a non-object in *&lt;htdocs&gt;*/owncloud8a1/lib/private/updater.php on line 84

### LINKED ISSUE #69: OC8 alpha2: updater is broken
### Steps to reproduce
1. log in as admin user
2. go to the admin panel
3. click Updater in the left panel
4. click the "Open Update Center" button

### Expected behaviour
The update center should open, I guess.

### Actual behaviour
following error message is shown:
Fatal error: Call to a member function getValue() on a non-object in /usr/local/apache2/htdocs/owncloud8/lib/private/updater.php on line 84

### Server configuration
**Operating system**: 
Slackware Linux x64

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 5.5.40

**PHP version:**
5.5.19

**ownCloud version:** (see ownCloud admin page)
8 alpha 2

**Updated from an older ownCloud or fresh install:**
updated from OC8 alpha 1 (manual installation)
this updater problem was present in OC8 alpha 1 as well

**List of activated apps:**
Since I can't enable any app (another issue with OC8),
only the default OC8 apps are active currently.

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'octgvzn2tj6m',
  'trusted_domains' => 
  array (
    0 => 'aivpc80',
  ),
  'datadirectory' => '/home/oc8data/',
  'overwrite.cli.url' => 'http://aivpc80/owc8',
  'dbtype' => 'mysql',
  'version' => '8.0.0.2',
  'dbname' => 'oc8',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
);

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Firefox 34

**Operating system:**
Slackware Linux 14.1

#### Web server error log
```
[Thu Jan 08 15:04:31.807946 2015] [mpm_event:notice] [pid 4705:tid 139653527857024] AH00489: Apache/2.4.10 (Unix) PHP/5.5.19 configured -- resuming normal operations
[Thu Jan 08 15:04:31.808248 2015] [core:notice] [pid 4705:tid 139653527857024] AH00094: Command line: '/usr/local/apache2/bin/httpd'
[Thu Jan 08 15:04:43.154552 2015] [access_compat:error] [pid 4791:tid 139653306423040] [client 134.184.28.151:45403] AH01797: client denied by server configuration: /usr/local/apache2/htdocs/owncloud8/data/htaccesstest.txt
[Tue Jan 13 16:01:21.630074 2015] [access_compat:error] [pid 4791:tid 139653067761408] [client 134.184.28.151:45527] AH01797: client denied by server configuration: /usr/local/apache2/htdocs/owncloud8/data/htaccesstest.txt
[Tue Jan 13 17:00:30.613154 2015] [access_compat:error] [pid 4706:tid 139653298030336] [client 134.184.28.151:45532] AH01797: client denied by server configuration: /usr/local/apache2/htdocs/owncloud8/data/htaccesstest.txt
[Wed Jan 14 11:33:07.159718 2015] [access_compat:error] [pid 4707:tid 139653339993856] [client 134.184.28.151:45634] AH01797: client denied by server configuration: /usr/local/apache2/htdocs/owncloud8/data/htaccesstest.txt

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"30bdfac704c50c89e71e7f5c1ae7b3fa","remoteAddr":"134.184.28.72","app":"no app in context","message":"Accessing the server container is deprecated. Use type annotations to inject core services instead!","level":2,"time":"2015-01-13T15:56:59+00:00"}
{"reqId":"90903fc14370c0520d76085f9bad3e7f","remoteAddr":"134.184.28.72","app":"no app in context","message":"Accessing the server container is deprecated. Use type annotations to inject core services instead!","level":2,"time":"2015-01-13T15:57:05+00:00"}
{"reqId":"c2941d4583508078db3831ea8b01529f","remoteAddr":"134.184.28.72","app":"no app in context","message":"Accessing the server container is deprecated. Use type annotations to inject core services instead!","level":2,"time":"2015-01-13T15:57:05+00:00"}
{"reqId":"25d07be4228610b90b209457332ee556","remoteAddr":"134.184.28.72","app":"no app in context","message":"Accessing the server container is deprecated. Use type annotations to inject core services instead!","level":2,"time":"2015-01-13T15:57:06+00:00"}
{"reqId":"61ef58d908c959cf11fe4aad922f8e25","remoteAddr":"134.184.28.72","app":"no app in context","message":"Accessing the server container is deprecated. Use type annotations to inject core services instead!","level":2,"time":"2015-01-13T15:57:06+00:00"}
{"reqId":"d24474c9a64d48cfe30750bc8b799734","remoteAddr":"134.184.28.72","app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/usr\/local\/apache2\/htdocs\/owncloud8\/apps\/updater\/update.php on line 27 and defined at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#46","level":3,"time":"2015-01-13T16:00:48+00:00"}
{"reqId":"d24474c9a64d48cfe30750bc8b799734","remoteAddr":"134.184.28.72","app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/usr\/local\/apache2\/htdocs\/owncloud8\/apps\/updater\/update.php on line 27 and defined at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#46","level":3,"time":"2015-01-13T16:00:48+00:00"}
{"reqId":"d24474c9a64d48cfe30750bc8b799734","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: httpHelper at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#47","level":3,"time":"2015-01-13T16:00:48+00:00"}
{"reqId":"d24474c9a64d48cfe30750bc8b799734","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: config at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#49","level":3,"time":"2015-01-13T16:00:48+00:00"}
{"reqId":"d24474c9a64d48cfe30750bc8b799734","remoteAddr":"134.184.28.72","app":"PHP","message":"Call to a member function getValue() on a non-object at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#84","level":3,"time":"2015-01-13T16:00:48+00:00"}
{"reqId":"ccb602ba6b98dbc814834ae55d8ca5c1","remoteAddr":"134.184.28.72","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-01-13T16:12:52+00:00"}
{"reqId":"61438ab0a7088408ef1ed992c402a970","remoteAddr":"134.184.28.72","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-01-13T16:12:59+00:00"}
{"reqId":"c7bda8ccd84faaef695b9ba7619539c8","remoteAddr":"134.184.28.72","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-01-13T16:13:09+00:00"}
{"reqId":"f5d3d1faf4c8dd70e8b0154c67a5e5ed","remoteAddr":"134.184.28.72","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-01-13T16:13:17+00:00"}
{"reqId":"9a22f742ca93e790c40f9dd16cac8d5e","remoteAddr":"134.184.28.72","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-01-14T10:19:05+00:00"}
{"reqId":"e619b8556169690b9fca43e61ea89192","remoteAddr":"134.184.28.72","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-01-14T10:19:13+00:00"}
{"reqId":"6834795b3838bc4267db2442b463a88c","remoteAddr":"134.184.28.72","app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/usr\/local\/apache2\/htdocs\/owncloud8\/apps\/updater\/update.php on line 27 and defined at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#46","level":3,"time":"2015-01-14T10:33:21+00:00"}
{"reqId":"6834795b3838bc4267db2442b463a88c","remoteAddr":"134.184.28.72","app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/usr\/local\/apache2\/htdocs\/owncloud8\/apps\/updater\/update.php on line 27 and defined at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#46","level":3,"time":"2015-01-14T10:33:21+00:00"}
{"reqId":"6834795b3838bc4267db2442b463a88c","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: httpHelper at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#47","level":3,"time":"2015-01-14T10:33:21+00:00"}
{"reqId":"6834795b3838bc4267db2442b463a88c","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: config at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#49","level":3,"time":"2015-01-14T10:33:21+00:00"}
{"reqId":"6834795b3838bc4267db2442b463a88c","remoteAddr":"134.184.28.72","app":"PHP","message":"Call to a member function getValue() on a non-object at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#84","level":3,"time":"2015-01-14T10:33:21+00:00"}
{"reqId":"c932899c98b08dac3d43af64a33ba00d","remoteAddr":"134.184.28.72","app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/usr\/local\/apache2\/htdocs\/owncloud8\/apps\/updater\/update.php on line 27 and defined at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#46","level":3,"time":"2015-01-14T10:35:10+00:00"}
{"reqId":"c932899c98b08dac3d43af64a33ba00d","remoteAddr":"134.184.28.72","app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/usr\/local\/apache2\/htdocs\/owncloud8\/apps\/updater\/update.php on line 27 and defined at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#46","level":3,"time":"2015-01-14T10:35:10+00:00"}
{"reqId":"c932899c98b08dac3d43af64a33ba00d","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: httpHelper at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#47","level":3,"time":"2015-01-14T10:35:10+00:00"}
{"reqId":"c932899c98b08dac3d43af64a33ba00d","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: config at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#49","level":3,"time":"2015-01-14T10:35:10+00:00"}
{"reqId":"c932899c98b08dac3d43af64a33ba00d","remoteAddr":"134.184.28.72","app":"PHP","message":"Call to a member function getValue() on a non-object at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#84","level":3,"time":"2015-01-14T10:35:10+00:00"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #66 
Fixes #69

### CODE REVIEW

**Comment by VicDeo** [comment]
@te-online @canepan @karlitschek

**Comment by te-online** [comment]
Looks good :+1: (and becomes more clear to me now ;-))

**Comment by DeepDiver1975** [comment]
API breakage like this should have been detected by unit tests ...

**Comment by VicDeo** [comment]
And how unit test should look like?

```
public function testIfCoreIsNotIntroducedSomethingUnknown(){
   new \OC\Updater(\OC::$server->getHTTPHelper(), \OC::$server->getAppConfig());
}

?

**Comment by DeepDiver1975** [comment]
> And how unit test should look like?

More in the sense of

```php

public function testAllTheInsanceLogicOfAjaxBackupPhp() {
}

**Comment by VicDeo** [comment]
Travis stuck. Superseded by https://github.com/owncloud/updater/pull/70

**Pull request closed without merging**
