### PR TITLE
Fix update wizard li-floating

### PR DESCRIPTION
**Pull request by mcnesium**
eeroh5fi
 -> 
xe3teup8

### CODE REVIEW

**Comment by te-online** [comment]
That's also fixed by this one https://github.com/owncloud/updater/pull/82

**Comment by VicDeo** [comment]
@te-online yes, but this one is safe to backport :)

**Comment by VicDeo** [comment]
:+1:

**Comment by te-online** [comment]
@VicDeo That's correct :+1:

**Comment by VicDeo** [comment]
@karlitschek the reason why I'm merging this PR is stable7/stable8 backport. This is a CSS oneliner.
But I should ask this question anyway: Backport?

**Comment by karlitschek** [comment]
hehe. fine with me :-)

**Pull request merged**
