### PR TITLE
Use updater.server.url

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes https://github.com/owncloud/core/issues/26199

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 @davitol

**Comment by PVince81** [comment]
Code looks good :+1: 

@davitol mind testing ?

**Comment by davitol** [comment]
:+1: Tested and update went fine
btw, should this PR be 'backported' to stable8.1 and stable8.0?

stable8.1:
https://github.com/owncloud/updater/blob/stable8.1/lib/app.php#L41-L43

stable8.0
https://github.com/owncloud/updater/blob/stable8/lib/app.php#L37-L40

@VicDeo @PVince81

**Comment by PVince81** [comment]
@davitol I think these old versions don't have the settings, that's where we had to use sed when testing.

**Comment by PVince81** [comment]
Looks like we do have them there.

@VicDeo please backport

**Comment by PVince81** [comment]
Backport to 8.1, 8.0 ? (note that the next 8.0 will be the last release before EOL)

**Comment by VicDeo** [comment]
@PVince81 not needed fot stable8/stable8.1
They use `\OC\Updater` class from core and do not pass the server URL since
Stable8.1: https://github.com/owncloud/updater/pull/381
Stable8: https://github.com/owncloud/updater/pull/382
So the config should be reused in core

**Pull request merged**
