### PR TITLE
[Stable9.1] Retrigger integrity check. Fixes #404

### LINKED ISSUE #404: Retrigger integrity scan at the end of the update
Current versions of the updater (9.0.5?) are running the full `occ upgrade` during the update, and after that they will update the "updater/" folder. The `occ ugprade` command implicitly triggers an integrity scan, which happens too early. So the results of this scan will contain errors for files under "updater/".

Goal is to add an additional step after updating the "updater/" folder. The step must retrigger the integrity scan to make sure that the latest "updater/" folder is included.

The workaround for now for users is to manually trigger a rescan in the admin page.
This isn't ideal.

@VicDeo @davitol

### PR DESCRIPTION
**Pull request by VicDeo**
Backport of https://github.com/owncloud/updater/pull/405

### CODE REVIEW

**Comment by VicDeo** [comment]
To test:

1. Install  9.1.0 or 9.1.1
2.  Patch it with https://gist.github.com/VicDeo/937a0172a06d693258b97b7132c4ba5b 
`patch -p0 < updater-910-911.patch`
3. Patch it with this PR
3. patch stable9.1 daily zip with  https://github.com/owncloud/core/pull/26482
4. Update to patched daily

Expected behavior: 
only `core/Controllers/OccController.php` should be reported as modified

**Comment by davitol** [comment]
@VicDeo @PVince81  After the update following your testing steps:
 
```
- core
	- FILE_MISSING
		- COPYING
	- INVALID_HASH
		- core/Controller/OccController.php
```

> Expected behavior:
> only core/Controllers/OccController.php should be reported as modified

So i guess :+1:

**Comment by VicDeo** [comment]
@davitol
`COPYING` is in daily master
stable9.1 should have `COPYING-AGPL` instead

but it doesn't matter I think

**Comment by davitol** [comment]
@VicDeo the original oC server was owncloud-9.1.1.tar.bz2 and it was updated via daily channel to owncloud-daily-master 😟

**Comment by PVince81** [comment]
that one "COPYING" change would need yet another patch, I think we're fine ?

**Comment by VicDeo** [comment]
@PVince81 exactly

**Pull request merged**
