### PR TITLE
Broken updater fixes

### PR DESCRIPTION
**Pull request by VicDeo**
1. use any RC
2. Switch to daily channel
3. Click `Update`
4. Observe Error 500

### CODE REVIEW

**Comment by PVince81** [comment]
10.0.1, it's too late for 10.0.

What ticket does this fix ? severity ?

**Comment by VicDeo** [comment]
@PVince81 the ticket that we will have in future when updates for 10.0 are available

**Comment by VicDeo** [comment]
@PVince81 please review

**Comment by PVince81** [comment]
Please explain the issue, I can't easily infer it from the code.

**Comment by VicDeo** [comment]
@PVince81 if
>use any RC
Switch to daily channel
Click Update
Observe Error 500

Is too long I'd describe it just as "Updater page for OC 10 is completely blank and doesn't work at all"

**Comment by VicDeo** [comment]
screenshot_20170503_213539
`Open Updater` click result

**Comment by PVince81** [comment]
I mean what is the root cause ? Why does it fail ? Is it due to a version parsing issue ? Is it not supposed to run the DB upgrade steps ?

**Comment by VicDeo** [comment]
@PVince81 
>I mean what is the root cause ?

1. my stupidity
2. incompletely removed code in https://github.com/owncloud/updater/pull/420
3. https://github.com/owncloud/updater/pull/413

**Comment by PVince81** [comment]
@VicDeo fair enough, thanks for the clarification 👍

**Comment by VicDeo** [comment]
[patched-10.0.0.zip](https://github.com/owncloud/updater/files/1038673/patched-10.0.0.zip)

**Pull request merged**
