### PR TITLE
Do not disable/reenable non-shipped apps

### PR DESCRIPTION
**Pull request by VicDeo**
Web Updater continues to disable/reenable non-shipped apps. This PR fixes that. 
This should be in 10.0 IMO.

Tested manually by copying files on top of 9.1.6 and updating to 10.0.2.1

Fixes disabling of encryption app described in  https://github.com/owncloud/updater/issues/428

### CODE REVIEW

**Comment by davitol** [comment]
👎 https://github.com/owncloud/updater/issues/428 Keeps reproducing. The default encryption module gets disabled.

**Comment by 4nanook** [comment]
The apps don't even showed up in disabled apps.

**Comment by davitol** [comment]
> The apps don't even showed up in disabled apps.

They are shown in my server. Enabling them again solved my problem

**Comment by 4nanook** [comment]
Are you running PHP 5.x or 7.x?

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by davitol** [comment]
> Are you running PHP 5.x or 7.x?

php 7.0

**Comment by 4nanook** [comment]
Hmm, I enabled apps once, but they do not show up in the upper left like
they used to even after enabling them.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by PVince81** [comment]
I agree with the approach, but it needs to work.

**Comment by VicDeo** [comment]
@PVince81 It works as advertised (Updater does not send app disabling/enabling requests to the core). 
Without this PR all 3rdparty apps will be disabled with a probability of 100%.

May be something else in a different repo needs a special attention. Should we experience a composition of different issues or just let this in and go further?

**Comment by PVince81** [comment]
@VicDeo is there another way to confirm that this is working when testing, something that does not involve encryption to validate the current changes ?

**Comment by VicDeo** [comment]
@PVince81 manual testing. E.g. with encryption disabled.
I tested it on my own 9.1.6 to 10

**Comment by davitol** [comment]
> Without this PR all 3rdparty apps will be disabled with a probability of 100%.

Let's merge this PR then

**Pull request merged**
