### PR TITLE
[Stable9.1] web executor

### PR DESCRIPTION
**Pull request by VicDeo**
Backport of https://github.com/owncloud/updater/pull/355

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by VicDeo** [comment]
@PVince81 9.1 or 9.1.1?

**Comment by PVince81** [comment]
Let's do 9.1.

@DeepDiver1975 @georgehrke second review ?

Once all this is merged we'll ask @owncloud/qa to redo update testing in the web UI for stable9/stable9.1/master

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
