### PR TITLE
Change include path instead of prepending

### LINKED ISSUE #86: Update to 8.0.2: Cannot redeclare class OC\Security\SecureRandom
Got stuck on step 3 "replace".
Admin log entry said:
"Cannot redeclare class OC\Security\SecureRandom at /MY_WWW_PATH/owncloud/lib/private/security/securerandom.php#24"

<hr/>
**Edit by @LukasReschke: A workaround can be found at https://github.com/owncloud/updater/issues/86#issuecomment-99187323**

**Edit by @VicDeo: And final fix is https://github.com/owncloud/updater/issues/86#issuecomment-85592285**

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #86 and #91

### CODE REVIEW

**Comment by VicDeo** [comment]
@karlitschek requesting backport to stable8

**Comment by karlitschek** [comment]
please backport :-)

**Comment by VicDeo** [comment]
Stable8 https://github.com/owncloud/updater/pull/108

**Comment by nicolasbonnici** [comment]
Work perfectly here for 8.0.2 to 8.1.1 migration.

Thank you

**Pull request merged**
