### PR TITLE
Move updater to admin page and add manual backup option

### PR DESCRIPTION
**Pull request by te-online**
If required I can also separate the two changes. The *move-to-admin* branch is a duplicate of this branch at the moment with the exception that it doesn't include the manual backup option.

### CODE REVIEW

**Comment by te-online** [comment]
Addresses https://github.com/owncloud/updater/issues/40 and https://github.com/owncloud/updater/issues/75.

**Comment by te-online** [comment]
@jancborchardt @VicDeo

Please tell me, if I've done anything wrong in the whole process or forgot anything important – I'm still new to this ;-)

**Comment by te-online** [comment]
Automated test seems to have a problem with the new *getFeed* method...
I think *apptest.php* might have to be changed, but I don't know how?

> 1) Test_Updater_App::testGetFeed
>
>Argument 2 passed to OC\Updater::__construct() must implement interface OCP\IConfig, instance of Mock_AppConfig_16b1059b given, called in /home/travis/build/owncloud/core/apps/updater/lib/app.php on line 37 and defined

**Comment by jancborchardt** [comment]
@te-online nice, thank you! :) Yes, it would probably be good to separate these two changes since they are not related. Would be awesome if you can do that.

cc @DeepDiver1975 for reference.

**Comment by DeepDiver1975** [comment]
> Automated test seems to have a problem with the new getFeed method...
> I think apptest.php might have to be changed, but I don't know how?

yes this is a breaking change which was introduced recently - https://github.com/owncloud/updater/pull/81 is required to be backported to the master branch

**Comment by te-online** [comment]
@jancborchardt Okay, thanks for your reply! :-) 
I can do a pull request for the *move-to-admin* branch first. But the *manual-backup* is based on the other changes, so I can create a request for that only when the rest is merged to master in some way.
@DeepDiver1975 okay, i understand

**Comment by jancborchardt** [comment]
@te-online yeah, that sounds good! First the move-to-admin, then the manual-backup one. :)

**Pull request closed without merging**
