### PR TITLE
Do not create __apps dir.

### LINKED ISSUE #290: Updater fails when __apps directory is already present (from 9.0)
As folloup problem of https://github.com/owncloud/core/issues/23469
(Note, there was no error reported after upgrading and the __apps directory was not removed automatically after the successful update)

Running: 
``sudo chown -R www-data:www-data .``
``sudo -uwww-data php updater/application.php``

````
ownCloud updater 1.0 - CLI based ownCloud server upgrades
Checking system health.
 - file permissions are ok.
Current version is 9.0.0.19
ownCloud daily is found online
What would you do next?
  [0] download
  [1] upgrade
  [2] abort
 > 1
Downloaded 100% (22773595 of 22773595)
Creatsoed checkpoint 9.0.0.19-56f117132b296
 simulated (optionally, can be done online in advance)
real [danger, might take long]
Extracting source into /var/www/owncloud/_oc_upgrade/100.0.0.0
PHP Warning:  rename(/var/www/owncloud/apps,/var/www/owncloud/__apps): File exists in /var/www/owncloud/updater/src/Utils/FilesystemHelper.php on line 129
PHP Stack trace:
PHP   1. {main}() /var/www/owncloud/updater/application.php:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/owncloud/updater/application.php:35
PHP   3. Owncloud\Updater\Console\Application->doRun() /var/www/owncloud/updater/vendor/symfony/console/Application.php:120
PHP   4. Symfony\Component\Console\Application->doRun() /var/www/owncloud/updater/src/Console/Application.php:111
PHP   5. Owncloud\Updater\Console\Application->doRunCommand() /var/www/owncloud/updater/vendor/symfony/console/Application.php:189
PHP   6. Symfony\Component\Console\Application->doRunCommand() /var/www/owncloud/updater/src/Console/Application.php:127
PHP   7. Symfony\Component\Console\Command\Command->run() /var/www/owncloud/updater/vendor/symfony/console/Application.php:838
PHP   8. Owncloud\Updater\Command\StartCommand->execute() /var/www/owncloud/updater/vendor/symfony/console/Command/Command.php:256
PHP   9. Owncloud\Updater\Console\Application->doRun() /var/www/owncloud/updater/src/Command/StartCommand.php:66
PHP  10. Symfony\Component\Console\Application->doRun() /var/www/owncloud/updater/src/Console/Application.php:111
PHP  11. Owncloud\Updater\Console\Application->doRunCommand() /var/www/owncloud/updater/vendor/symfony/console/Application.php:189
PHP  12. Symfony\Component\Console\Application->doRunCommand() /var/www/owncloud/updater/src/Console/Application.php:127
PHP  13. Symfony\Component\Console\Command\Command->run() /var/www/owncloud/updater/vendor/symfony/console/Application.php:838
PHP  14. Owncloud\Updater\Command\ExecuteCoreUpgradeScriptsCommand->execute() /var/www/owncloud/updater/vendor/symfony/console/Command/Command.php:256
PHP  15. Owncloud\Updater\Utils\FilesystemHelper->move() /var/www/owncloud/updater/src/Command/ExecuteCoreUpgradeScriptsCommand.php:104
PHP  16. rename() /var/www/owncloud/updater/src/Utils/FilesystemHelper.php:129



  [Exception]
  Unable to move /var/www/owncloud/apps to /var/www/owncloud/__apps



upgrade:executeCoreUpgradeScripts
````

Script ended here without further notice.

### LINKED ISSUE #332: Move __apps into data folder
https://github.com/owncloud/updater/blob/8b971f9631aa6a6015ead3b48c7d8c72c24860f2/src/Command/ExecuteCoreUpgradeScriptsCommand.php#L106

Related to https://github.com/owncloud/updater/issues/331

### LINKED ISSUE #336: Upgrade from 9.0 to 9.1 fails
### Steps to reproduce
1. Install daily stable9 tarball (9.0.1 (daily) Build:2016-04-26T03:20:01+00:00 6c861f71eb62e9cee2617a472bcd6d37bfd7b899)
2. Make sure the updater downloads the daily master package (*)
3. Run the updater

### Expected behaviour
Updater upgrades to 9.1

### Actual behaviour
Upgrade fails

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 9.1.0 pre alpha 2016-04-26T03:08:09+00:00 d8f327831e6f64658c50131c2e7344ee6fa0e86a

**Updated from an older ownCloud or fresh install:** updated from 9.0.1 daily

### Updater trace
```
ownCloud updater 1.0 - CLI based ownCloud server upgrades
Checking system health.
 - file permissions are ok.
Current version is 9.0.1.3
Online version is 100.0.0.0 [daily]
What would you do next?
  [0] download
  [1] upgrade
  [2] abort
 > 1
Downloaded 100% (35076540 of 35076540)
Created checkpoint 9.0.1.3-571f8686a86f2
 simulated (optionally, can be done online in advance)
real [danger, might take long]
Extracting source into /opt/owncloud/data/updater-data/_oc_upgrade/100.0.0.0
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)


Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Reset log level

Upgrading the application activity
PHP Fatal error:  Call to protected method Owncloud\Updater\Utils\FilesystemHelper::rmdirr() from context 'Owncloud\Updater\Command\UpgradeShippedAppsCommand' in /opt/owncloud/updater/src/Command/UpgradeShippedAppsCommand.php on line 75
```

### Update.log
```
[info] Execution of upgrade:start command started
[info] Execution of upgrade:info command started
[info] Execution of upgrade:info command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.0.1.3 found
[info] Execution of upgrade:detect command stopped. Exit code is 4
[info] Execution of upgrade:start command stopped. Exit code is 0
[info] Execution of upgrade:start command started
[info] Execution of upgrade:info command started
[info] Execution of upgrade:info command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.0.1.3 found
[info] Execution of upgrade:detect command stopped. Exit code is 128
[info] Execution of upgrade:start command stopped. Exit code is 0
[info] Execution of upgrade:start command started
[info] Execution of upgrade:info command started
[info] Execution of upgrade:info command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.0.1.3 found
[info] Execution of upgrade:detect command stopped. Exit code is 0
[info] Execution of upgrade:backupDb command started
[info] Execution of upgrade:backupDb command stopped. Exit code is 0
[info] Execution of upgrade:backupData command started
[info] Execution of upgrade:backupData command stopped. Exit code is 0
[info] Execution of upgrade:checkpoint command started
[info] Execution of upgrade:checkpoint command stopped. Exit code is 0
[info] Execution of upgrade:preUpgradeRepair command started
[info] Execution of upgrade:preUpgradeRepair command stopped. Exit code is 0
[info] Execution of upgrade:dbUpgrade command started
[info] Execution of upgrade:dbUpgrade command stopped. Exit code is 0
[info] Execution of upgrade:dbUpgrade command started
[info] Execution of upgrade:dbUpgrade command stopped. Exit code is 0
[info] Execution of upgrade:disableNotShippedApps command started
[info] Execution of upgrade:disableNotShippedApps command stopped. Exit code is 0
[info] Execution of upgrade:executeCoreUpgradeScripts command started
[debug] Replacing 3rdparty
[debug] Replacing config/config.sample.php
[debug] Replacing core
[debug] Replacing l10n
[debug] Replacing lib
[debug] Replacing ocs
[debug] Replacing ocs-provider
[debug] Replacing resources
[debug] Replacing settings
[debug] Replacing .htaccess
[debug] Replacing .mailmap
[debug] Replacing .tag
[debug] Replacing .user.ini
[debug] Replacing AUTHORS
[debug] Replacing console.php
[debug] Replacing COPYING-AGPL
[debug] Replacing cron.php
[debug] Replacing db_structure.xml
[debug] Replacing index.html
[debug] Replacing index.php
[debug] Replacing indie.json
[debug] Replacing occ
[debug] Replacing public.php
[debug] Replacing remote.php
[debug] Replacing robots.txt
[debug] Replacing status.php
[debug] Replacing version.php
[info] Execution of upgrade:executeCoreUpgradeScripts command stopped. Exit code is 0
[info] Execution of upgrade:upgradeShippedApps command started
```

(*) The url where the updater downloads the file changed to make sure the daily master package (9.1) is downloaded for the current version. In addition, the build date of the current version (9.0.1) was modified (it was set 2 days ago), probably needed for the server side.

Probably related to https://github.com/owncloud/updater/issues/335

### PR DESCRIPTION
**Pull request by VicDeo**
Depends on https://github.com/owncloud/updater/pull/346
Fixes https://github.com/owncloud/updater/issues/264
Fixes #336 
Fixes #290
Closes #332

takes care of https://github.com/owncloud/updater/issues/336#issuecomment-216172639
- [x] we should replace all shipped apps at once and run upgrade once - doing this step by step is wrong

### CODE REVIEW

**Comment by Phiber2000** [comment]
Code looks fine.
:+1:

**Comment by VicDeo** [comment]
@Phiber2000 Thanks, but it's not 100% completed yet :)

**Comment by Phiber2000** [comment]
I was afraid. But it's a nice start fixing this ugly folder workaround!
I hope there will not be too much trouble with apps...

**Comment by VicDeo** [comment]
Finally

**Comment by VicDeo** [comment]
@DeepDiver1975 @PVince81 @LukasReschke

**Comment by PVince81** [comment]
How to test ?

**Comment by VicDeo** [comment]
@PVince81 
1. Install https://owncloud.org/community/owncloud-daily-stable9.zip
2. Switch update channel to `daily`
3. Override Feed url https://github.com/owncloud/updater/blob/master/src/Utils/Feed.php#L108 with 'https://owncloud.org/community/owncloud-daily-master.zip'
4. `php updater/application upgrade:start`

**Comment by davitol** [comment]
@VicDeo The patch did not worked for me following your steps above

This was the output:

cURL error 3: <url> malformed
Done


Please feel free to chat with me via IRC related to my test or my test environment

**Comment by VicDeo** [comment]
@davitol 
https://github.com/owncloud/updater/blob/master/src/Utils/Feed.php#L108
`return $this->url;`
should be replaced with 
`return 'https://owncloud.org/community/owncloud-daily-master.zip';`

**Comment by davitol** [comment]
> @davitol
> https://github.com/owncloud/updater/blob/master/src/Utils/Feed.php#L108
> return $this->url;
> should be replaced with
> return 'https://owncloud.org/community/owncloud-daily-master.zip';

@VicDeo already done

**Comment by VicDeo** [comment]
@davitol.. oops wrong links
`https://download.owncloud.org/community/owncloud-daily-master.zip`

**Comment by davitol** [comment]
@VicDeo in your comment https://github.com/owncloud/updater/pull/347#issuecomment-216770993
seems to have the sames steps than before even when it has been edited

**Comment by davitol** [comment]
@VicDeo 

screen shot 2016-05-04 at 10 42 59

**Comment by VicDeo** [comment]
@davitol try adding `sudo -u www-data` as suggested

**Comment by davitol** [comment]
@VicDeo Yes, this time i forgot to change the user and www-data solved the previous screenshot, but the error:
cURL error 3: <url> malformed
keeps happening when running the command.

**Comment by davitol** [comment]
@VicDeo Trying again from zero and following the steps, this is what I got while running:
php updater/application.php upgrade:start

```
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Reset log level

PHP Fatal error:  Call to protected method Owncloud\Updater\Utils\Checkpoint::getCheckpointPath() from context 'Owncloud\Updater\Command\EnableNotShippedAppsCommand' in /opt/owncloud/updater/src/Command/EnableNotShippedAppsCommand.php on line 52
```

**Comment by VicDeo** [comment]
@davitol er. https://github.com/owncloud/updater/pull/346 has been not ported to stable9 yet. 
(and is not shipped with daily)

**Comment by davitol** [comment]
:+1: Tested and works

**Comment by VicDeo** [comment]
@DeepDiver1975 @LukasReschke @PVince81 more reviewers plz :santa:

**Comment by PVince81** [comment]
Code looks fine :+1:

**Comment by PVince81** [comment]
@karlitschek @LukasReschke @DeepDiver1975 backport to 9.0.3 ?

**Comment by karlitschek** [comment]
i think this makes sense. please backport :+1:

**Comment by VicDeo** [comment]
Stable9: https://github.com/owncloud/updater/issues/352

**Comment by wolfsden3** [comment]
Why is this crap so buggy?  Seriously you guys don't test this stuff?  I get this:
[Symfony\Component\Process\Exception\ProcessFailedException]
  The command "php /var/www/owncloud/occ --no-warnings app:list --output=json
   '--shipped false'" failed.
  Exit Code: 1(General error)
  Output:
  ================
  Error Output:
  ================

    [Symfony\Component\Console\Exception\RuntimeException]
    The "--shipped false" option does not exist.

  app:list [--output [OUTPUT]] [--shipped SHIPPED]

...I don't understand how an upgrade for you could be so smooth when everyone elses installation is borked like mine!

**Comment by PVince81** [comment]
@wolfsden3 https://owncloud.org/community/code-of-conduct/

Upgrades were tested with the updater and they worked in many environments. If they didn't in your specific environment, the only helpful thing you could do here is provide more information about it.

**Comment by wolfsden3** [comment]
If I don't use your updater and use the one in the OC 9 manual my upgrade now works where before it did not so the stable 9.1 on the website is broken in my opinion for Ubuntu.  I've been trying to fix the stupid no smb mount (external storage not available error) which is a whole host of other bugs and this is all just so frustrating including the error I got with your fixes that supposedly fixed my problem and didn't.  External storage works in 8.x so maybe I'll dump my Ubuntu 16 install and OC 9.x.

SMB bug:  https://github.com/owncloud/core/pull/21481

Anyway...my upgrade works if I don't use your updater so I'm not sure what your updater fixes!

/var/www/owncloud# sudo -u www-data php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level

I then take it out of maintenance mode and start Apache2 and it works again but the SMB mount still doesn't.  I'm still looking online for fixes but not coming up with anything.

I'm not expecting you to help with the SMB issue just letting people know your updater isn't a fix for everyone I guess.

**Pull request merged**
