### PR TITLE
Add release channels support

### PR DESCRIPTION
**Pull request by VicDeo**
Closes https://github.com/owncloud/updater/issues/95

### CODE REVIEW

**Comment by karlitschek** [comment]
looks great :+1: 
@jancborchardt @DeepDiver1975 What do you think about the UX part? It this clear enough for people to understand what is going on?

**Comment by jancborchardt** [comment]
2 things:
* There is no current channel selected by default. That needs to be fixed according to the version one is on.
* The sorting is: Production, Stable, Daily, Beta – shouldn’t Beta come before Daily?

Otherwise the layout is fine. But I’m not one to judge the code, and that is the bigger point here.

**Comment by VicDeo** [comment]
@jancborchardt 
>There is no current channel selected by default. That needs to be fixed according to the version one is on.

All released packages have `stable` as a default channel
I guess you tested it with git owncloud. it has 'git' set as a  channel and this value match none from this list https://github.com/owncloud/core/blob/master/version.php#L32

**Comment by karlitschek** [comment]
@jancborchardt @VicDeo are the channel names enough es explanation? Or do we add some kind of explanation text what this means?
I´m not sure.

**Comment by DeepDiver1975** [comment]
@VicDeo unit tests are falling apart - we changed the ctor of updater again afaik - THX

**Comment by VicDeo** [comment]
@DeepDiver1975 wel, pure DI drawback: nothing is actually broken but one needs to adapt tests. 
:tongue:

**Comment by VicDeo** [comment]
@DeepDiver1975 Fix is pushed

**Comment by Pazu** [comment]
Could this be backported to 7?

**Comment by VicDeo** [comment]
@Pazu unfortunately not. I'm not sure whether update server would support channels for 7.

Channel itself can be set here https://github.com/owncloud/core/blob/stable7/version.php#L15 (needs to be patched with each update)

**Pull request merged**
