### PR TITLE
Typo Fix

### PR DESCRIPTION
**Pull request by mmattel**
Small typo fix:
permissions fot --> permissions for

Backporting maybe necessary.

### CODE REVIEW

**Comment by VicDeo** [comment]
@mmattel thanks :+1:

**Comment by VicDeo** [comment]
@cmonteroluque A trivial change. Backport to stable9?

**Comment by cmonteroluque** [comment]
yes please!

**Comment by VicDeo** [comment]
Stable9: https://github.com/owncloud/updater/issues/353

**Pull request merged**
