### PR TITLE
Retrigger integrity check. Fixes #404

### LINKED ISSUE #404: Retrigger integrity scan at the end of the update
Current versions of the updater (9.0.5?) are running the full `occ upgrade` during the update, and after that they will update the "updater/" folder. The `occ ugprade` command implicitly triggers an integrity scan, which happens too early. So the results of this scan will contain errors for files under "updater/".

Goal is to add an additional step after updating the "updater/" folder. The step must retrigger the integrity scan to make sure that the latest "updater/" folder is included.

The workaround for now for users is to manually trigger a rescan in the admin page.
This isn't ideal.

@VicDeo @davitol

### PR DESCRIPTION
**Pull request by VicDeo**
To test:
- Core daily package needs to be patched with https://github.com/owncloud/core/pull/26469
- This patch is applied on top of the installed OC

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81

**Comment by davitol** [comment]
> To test:
> 
>     Core daily package needs to be patched with owncloud/core#26469
>     This patch is applied on top of the installed OC

1. Core daily package needs to be patched with owncloud/core#26469 done and host in my local update.server.
2. config.php in updater.server modified in order to get this patched oC
3. oC server master daily version patched with the current PR https://github.com/owncloud/updater/pull/405
4. version.php file is modified with a 3 days ago date
5. run update via webUI using daily channel


Current Behaviour:
- ```Could not parse a response for status. Please check if the current shell user can run occ command. Raw output: Not allowed ```   is shown via webUI
- ```{"reqId":"vQRsK9ZEIZUSEBM7ZlPw","remoteAddr":"172.17.0.1","app":"core","message":"Invalid request to occ controller. Details: \"Web executor is not allowed to run from a host 172.17.0.1\"","level":2,"time":"2016-10-25T08:38:51+00:00","method":"POST","url":"\/index.php\/occ\/status","user":"--"}```in owncloud.log

@VicDeo @PVince81 Is it needed to patch daily-master with other patch in other to avoid the web exceutor error?

**Comment by PVince81** [comment]
@davitol yes, very likely. I suggest you apply all previous patches (gist) to avoid update issues and then the one from this PR as well.

**Comment by VicDeo** [comment]
@davitol  it should be applied on the top of the current stable9/master (tomorrow's daily)
as soon as the fixes for `not allowed` have been just merged and aren't included in today's dailies

The are  #400 and #401

**Comment by davitol** [comment]
@VicDeo   
 1.   Core daily package needs to be patched with owncloud/core#26469 done and host in my local update.server.
 2.   config.php in updater.server modified in order to get this patched oC
 3.   oC server stable9.1 patched with PR #400 
 4.   version.php file is modified with a 3 days ago date
 5.  run update via webUI using daily channel
 6. Patch applied on the server after the update
 7. Remove .patch file

List of invalid files:

```
Results
=======
- core
	- INVALID_HASH
		- core/Controller/OccController.php
		- updater/src/Command/PostUpgradeCleanupCommand.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/Controller/OccController.php] => Array
                        (
                            [expected] => 00e3f0f97e8632ff1a788686c0d2f365d34e5bb362b19e6f5fc995fa0674e23a810636e5ba19caabc1653758af67c86db7edb2c65b2f2917cca8f80b122b065c
                            [current] => 75a19d8ac2d7e585375d1a581101ad1960cb292b52a2b4a400e4c73e692a4f8d4b672b425a31262e764e15002241272f5209aa8a84caacb4c46cb492c8c81a71
                        )

                    [updater/src/Command/PostUpgradeCleanupCommand.php] => Array
                        (
                            [expected] => 6c25a83ed4c31619fc0e894bace675c5f7ce363f97b24294fee05603451bc531384070e9163f858212d47c45fab97ee6794aa6925024383c85acf82028b4b321
                            [current] => 66cf94ca7e823ebdcaeecf4c36cefdf4c3b51da68dd443bfbbacc68ec97957e144714ce3308e586fdf1250c315ed8bf95dad692c782438733841cc7729c03a4f
                        )

                )

        )

)
```



> This patch is applied on top of the installed OC

I guess it means that it should be applied after updating when the server is in 9.2. status, no?

**Comment by VicDeo** [comment]
@davitol  these two files have incorrect signature because you patched them in order not to have the whole `updater` directory content under INVALID_HASH section.

Given that https://github.com/owncloud/core/pull/26469 is already merged If you recheck with the next daily there will be only PostUpgradeCleanupCommand.php in this list.

**Comment by davitol** [comment]
> @davitol these two files have incorrect signature because you patched them in order not to have the whole updater directory content under INVALID_HASH section.
> 
> Given that owncloud/core#26469 is already merged If you recheck with the next daily there will be only PostUpgradeCleanupCommand.php in this list.

@VicDeo @PVince81 Then if it looks fine with this behaviour :+1:
Note: also tested with '9.2' to master-daily and it had the same behaviour

**Comment by PVince81** [comment]
@VicDeo backport ?

**Comment by VicDeo** [comment]
Stable9.1: https://github.com/owncloud/updater/issues/407

**Pull request merged**
