### PR TITLE
[Stable9.1] Fallback to localhost and then to CLI

### LINKED ISSUE #397: Cannot update via webUI from 9.1.1. to daily
screen shot 2016-10-13 at 13 56 24
Applying the following patch to log the reason of the failure --> https://github.com/owncloud/core/pull/26277

I got in owncloud.log:

```
{"reqId":"LUPJWlCQ8mFArHTnlIiZ","remoteAddr":"172.17.0.1","app":"core","message":"Invalid request to occ controller. Details: \"Web executor is not allowed to run from a host 172.17.0.1\"","level":2,"time":"2016-10-13T12:03:02+00:00","method":"POST","url":"\/index.php\/occ\/config:list","user":"--"}
```
@VicDeo @PVince81

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #397

forwardport of the second commit from https://github.com/owncloud/updater/pull/395 to Stable9.1

### CODE REVIEW

**Comment by davitol** [comment]
@VicDeo @PVince81 
Tested in owncloud-daily-stable9.1 (14/10/2016) "version":"9.1.1.3","versionstring":"9.1.1","edition":
and it does NOT work for me 👎 

```
{"reqId":"MR58OsdvN7VnWce4zyr8","remoteAddr":"172.17.0.1","app":"core","message":"Invalid request to occ controller. Details: \"Web executor is not allowed to run from a host 172.17.0.1\"","level":2,"time":"2016-10-14T07:55:32+00:00","method":"POST","url":"\/index.php\/occ\/status","user":"--"}
```

**Comment by VicDeo** [comment]
@davitol tested with 9.1.1 and works :)

**Comment by VicDeo** [comment]
steps
1. Install 9.1.1
2. Apply this patch
3. Switch channel to daily
3. Upgrade

**Comment by PVince81** [comment]
@VicDeo today @davitol said that the patch doesn't apply on top of v9.1.1. So later on we'll need another patch that applies on top of v9.1.1 for people who need to patch manually.

**Comment by davitol** [comment]
@PVince81 @VicDeo Applying the changes by hand the update foes fine and the changes solve the issue :+1:

Applying on top of v9.1.1 this patch throws the following message:

```
patch -p1 < 398.patch 
patching file src/Console/Application.php
Hunk #1 FAILED at 153.
Hunk #2 succeeded at 190 (offset -8 lines).
1 out of 2 hunks FAILED -- saving rejects to file src/Console/Application.php.rej
patching file src/Utils/OccRunner.php
```

**Comment by PVince81** [comment]
@VicDeo please also forward port to master.

We'll also need another patch that works with v9.1.1 and possibly v9.1.0 (gist?) to put on central.

**Comment by PVince81** [comment]
> @VicDeo please also forward port to master.

Any update ? There were so many patches here and there that I lost track of them, so if this is already done, please remove the"backport-request" label.

**Comment by VicDeo** [comment]
@PVince81 
Submited  to master as https://github.com/owncloud/updater/pull/401

**Pull request merged**
