### PR TITLE
Fix endpoint detection

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes `cURL error 6: Could not resolve host: status` on master

### CODE REVIEW

**Comment by VicDeo** [comment]
Stable9.1: https://github.com/owncloud/updater/pull/394

**Comment by PVince81** [comment]
@VicDeo with all the recent patches, is this one still relevant ? Will it conflict ?

**Comment by VicDeo** [comment]
@PVince81 still relevant and already merged into stable9.1 already.

**Comment by PVince81** [comment]
ok...

**Pull request merged**
