### PR TITLE
 Use IConfig instead of IAppConfig

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
needs to be fixed in master as well @VicDeo

**Comment by MorrisJobke** [comment]
@DeepDiver1975 You know that IConfig and IAppConfig have different interfaces?

**Comment by MorrisJobke** [comment]
:-1: This will break! `\OC\Updater` needs to be adjusted as well.

**Comment by DeepDiver1975** [comment]
> :-1: This will break! \OC\Updater needs to be adjusted as well.

not this is the fix once #14518 is merged to stable8 :wink:

**Comment by MorrisJobke** [comment]
Got it :+1:

**Comment by MorrisJobke** [comment]
Sorry for the trouble

**Comment by PVince81** [comment]
I had this branch checked out while I tried https://github.com/owncloud/updater/pull/81

So I guess this means it worked :+1:

**Comment by PVince81** [comment]
I restarted the build

**Comment by DeepDiver1975** [comment]
> I restarted the build

hehe - me too ...

**Comment by DeepDiver1975** [comment]
:+1: build is fine

**Pull request merged**
