### PR TITLE
Drop PHP 7.1 support and update Guzzle

### PR DESCRIPTION
**Pull request by VicDeo**
- Drop PHP 7.1 support
- Update Guzzle library to 6.5 and get rid of Guzzle 5.3 with its unmaintained dependencies

### CODE REVIEW

**Comment by VicDeo** [comment]
@phil-davis it looks like Travis integration is broken in the Updater repo.  :(

**Comment by phil-davis** [comment]
@VicDeo IMO Travis is "broken" everywhere for open-source. We need to convert this repo to use drone.

**Comment by VicDeo** [comment]
Seems to be related:
https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by VicDeo** [comment]
Closing in favour of https://github.com/owncloud/updater/pull/592

**Pull request closed without merging**
