### PR TITLE
Stable8 fixups

### LINKED ISSUE #164: Updater is not copying over ca-bundle.crt?
Hi,

i'm not using the updater so i can't reproduce this but i have now read from three different people that they used the updater to go from 8.0.5 to 8.1.1 (https://github.com/owncloud/core/issues/17448#issuecomment-130879981) and afterwards the config/ca-bundle.crt was missing.

Anyone could try to reproduce this to avoid issues with failed connections to the appstore and similar problems.

### PR DESCRIPTION
**Pull request by VicDeo**
- use new update server URL
- cast SimpleElement  to string (it can be array of strings otherwise)
- copy crt bundle to `config` directory

Fixes #164 #134

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 @DeepDiver1975

**Comment by PVince81** [comment]
@VicDeo if we do proxy the server URL to the new one, will this PR/fix be required at all ?
From what I see it seems to fix more, so the answer is probably yes ?

**Comment by VicDeo** [comment]
@PVince81 yes, because it fixes two more issues.

**Comment by PVince81** [comment]
Code looks good, and now I also remember the cert bundle issue :+1: 

@owncloud/qa can you help testing ? It will need the usual local test server gymnastics.

**Comment by PVince81** [comment]
Tested as follows:

1. Download OC 8.0.14 tarball and install it
1. Patch the tarball's "apps/updater" folder with this PR
1. Change version.php and set the channel to "beta"
1. `delete from oc_appconfig where configkey='lastupdatedat';`
1. Go to admin page, open updater
1. Run update

Works fine :+1:

**Comment by PVince81** [comment]
@DeepDiver1975 quick second review ?

**Pull request merged**
