### PR TITLE
Suppress all warning from occ

### PR DESCRIPTION
**Pull request by VicDeo**

### CODE REVIEW

**Comment by PVince81** [comment]
Let me retest with https://github.com/owncloud/updater/issues/335

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
Second review @DeepDiver1975 @LukasReschke @icewind1991 ?

**Comment by LukasReschke** [comment]
As far I see this will only work for the update from 9.0.2 and upwards. Is this correct?

If so we need to add a workaround to core as well for this. – We shall not have an updater that is broken if PCNTL is not installed.

**Comment by PVince81** [comment]
@karlitschek backport to 9.0.2 ? Fixes updater issue when optional PCNTL module is not enabled, where the warning was messing up CLI output parsing :frowning:

**Comment by PVince81** [comment]
@LukasReschke likely. So maybe we need to add a fix in core as well to make it work ?
Apart from removing the warning I don't see a good way.

**Comment by VicDeo** [comment]
@LukasReschke 
>As far I see this will only work for the update from 9.0.2 and upwards. Is this correct?

true

**Comment by LukasReschke** [comment]
> Apart from removing the warning I don't see a good way.

Then we need to do that. Even if it sucks. – We can remove that with 9.0.3 then.

@VicDeo Mind opening a PR to core against stable9 that also works around this? THX:

**Comment by VicDeo** [comment]
@LukasReschke ok, in a couple of minutes

**Comment by VicDeo** [comment]
as per https://github.com/owncloud/updater/pull/339#issuecomment-214822987

Core PR https://github.com/owncloud/core/pull/24294
Revert Core PR for 9.0.3 https://github.com/owncloud/core/pull/24295

**Comment by LukasReschke** [comment]
👍

**Comment by PVince81** [comment]
@VicDeo please prepare the backport PR

**Comment by VicDeo** [comment]
@PVince81 backport https://github.com/owncloud/updater/pull/340

**Comment by karlitschek** [comment]
great. backport makes sense :+1:

**Pull request merged**
