### PR TITLE
fixes wrong invalid password ui

### PR DESCRIPTION
**Pull request by Phiber2000**
Thix fixes the message ui shown when wrong password was entered.
Maybe this had been forgotten in #265, #266.
ref issue #263

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by Phiber2000** [comment]
Common question belonging to merging procedures:
When backporting that/something, do I always have to wait for a thumb up again?

**Comment by LukasReschke** [comment]
2 thumbs up for master and for a backport also @karlitschek has to approve those before :-)

@karlitschek UI annoyance and no-brainer. Backport?

**Comment by LukasReschke** [comment]
And :rocket: :star:! Thank you for contributing to ownCloud :dancers:

**Comment by karlitschek** [comment]
backport :-)

**Comment by Phiber2000** [comment]
Thanks for answer! I haven't noticed that merging rules before. But these commits were foolproof and VicDeo had an eye on that #282.
However, sorry for that!

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
