### PR TITLE
Master forwardport fallback

### PR DESCRIPTION
**Pull request by VicDeo**
Forwardport of
https://github.com/owncloud/updater/pull/398
and
https://github.com/owncloud/updater/pull/400

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks. @davitol please test as well but with lower prio since this is master

**Comment by davitol** [comment]
@VicDeo 
screen shot 2016-10-20 at 11 23 06

**Comment by VicDeo** [comment]
@davitol thanks, looks like there is an error on the core side
 I'll check it.

**Comment by VicDeo** [comment]
@davitol does owncloud.log have related entries like `downgrade is not supported`?

**Comment by davitol** [comment]
@VicDeo Yes

```
{"reqId":"JSBqtiVxw7zxUWd+Xkz6","remoteAddr":"::1","app":"PHP","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/lib\/composer\/symfony\/console\/Input\/ArgvInput.php#260","level":3,"time":"2016-10-20T09:22:12+00:00","method":"POST","url":"\/index.php\/occ\/config:list","user":"--"}
{"reqId":"IjXOu87V1jwR0ccHF4pd","remoteAddr":"82.159.139.58","app":"remote","message":"Downgrading is not supported and is likely to cause unpredictable issues (from 9.2.0.2 to 9.1.1.3)","level":4,"time":"2016-10-20T09:25:35+00:00","method":"GET","url":"\/status.php","user":"admin"}
```

**Comment by VicDeo** [comment]
@davitol it's unrelated to updater
http://updates.owncloud.com/server//?version=9x2x0x0x5x6xdailyxdailyxabc

owncloud-daily-stable9.1.zip is offered for 9.2 (master)

**Comment by davitol** [comment]
:+1: Solves 
```
{"reqId":"vQRsK9ZEIZUSEBM7ZlPw","remoteAddr":"172.17.0.1","app":"core","message":"Invalid request to occ controller. Details: \"Web executor is not allowed to run from a host 172.17.0.1\"","level":2,"time":"2016-10-25T08:38:51+00:00","method":"POST","url":"\/index.php\/occ\/status","user":"--"}
```
error

**Comment by PVince81** [comment]
Please make a separate issue for https://github.com/owncloud/updater/pull/401#issuecomment-255055213

**Comment by VicDeo** [comment]
@PVince81 Submitted as https://github.com/owncloud/administration-internal/issues/39

**Comment by VicDeo** [comment]
and https://github.com/owncloud/updater/issues/406

**Pull request merged**
