### PR TITLE
Update to PHP 7.1 and phpunit 7.5

### PR DESCRIPTION
**Pull request by phil-davis**
Travis CI is already just testing PHP 7.1 7.2 7.3

This PR changes composer to specify minimum PHP 7.1 and that allows phpunit 7.*

This can be done if it is OK that this app will no longer run on PHP  7.0

### CODE REVIEW

**Comment by phil-davis** [comment]
`src/Console/Application.php` has:
```
		if (version_compare($installedVersion, '9.0.0', '<')){
			throw new \RuntimeException("Minimum ownCloud version 9.0.0 is required for the updater - $installedVersion was found in " . $locator->getOwnCloudRootPath());
		}
```
I guess that is still fine - a user can be on core version 9 and running PHP 7.1 and will be able to use this updater.

**Comment by phil-davis** [comment]
Rebased to resolve conflicts in `composer.lock`

**Comment by phil-davis** [comment]
Somehow my commit is not signed. I will try and fix that...

**Comment by VicDeo** [comment]
@phil-davis ouch... I merged symfony dependencies, `composer.lock` is conflicting now

**Comment by phil-davis** [comment]
I have rebased and sorted that out. Now let's see about my commit singing.

**Comment by phil-davis** [comment]
The magic command was:
```
git rebase --exec 'git commit --amend --no-edit -n -S' -i master
git push -f
```

**Pull request merged**
