### PR TITLE
Show version and channel instead of version string

### PR DESCRIPTION
**Pull request by VicDeo**
Ref #292 

Before:
Current version is 9.1.0.0
ownCloud daily is found online

After:
Current version is 9.1.0.0
Online version is 100.0.0.0 [daily]

### CODE REVIEW

**Comment by VicDeo** [comment]
@DeepDiver1975 @mmattel @PVince81

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by VicDeo** [comment]
@karlitschek backport?

**Comment by karlitschek** [comment]
definitely backport :+1:

**Comment by DeepDiver1975** [comment]
Are we going to maintain stable branches in here?
Does that make sense?

The updater will have to work with any past and any future version of owncloud core.

From my understanding there should be one stable version which can be pulled (somehow) to get the latest version.

Just asking - since this is all lacking a bit of concept and I want to wrap my brain around this ...

**Comment by VicDeo** [comment]
@DeepDiver1975 lets' discuss this separately in https://github.com/owncloud/updater/issues/295

**Comment by VicDeo** [comment]
Stable9: https://github.com/owncloud/updater/issues/296

**Pull request merged**
