### PR TITLE
Use 8.2

### LINKED ISSUE #189: Unable to move /srv/http/owncloud/_oc-upgrade/8.2.1.4/core/resources to /srv/http/owncloud/resources
Hi,

When I'm trying to upgrade from 8.2.0 to 8.2.1, I got the following issue:
upgrade

And also with "Something went wrong for core. Rolling back." in the logs.

Thanks,
HLFH

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #189

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Will need backport ?

**Comment by VicDeo** [comment]
@PVince81 yes, to 8.2

**Comment by karlitschek** [comment]
backport is fine! :+1:

**Pull request merged**
