### PR TITLE
Remove bogus redundant version number

### PR DESCRIPTION
**Pull request by PVince81**
Please review @VicDeo @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
Forgot to mention: "info.xml" said 0.5 but the "version" file said 0.6... and this caused update loops https://github.com/owncloud/core/issues/17457

**Comment by PVince81** [comment]
@karlitschek this will need a backport for 8.1.1

**Comment by karlitschek** [comment]
great :+1:  Please backport!

**Comment by PVince81** [comment]
Backport PR here https://github.com/owncloud/updater/pull/155

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
