### PR TITLE
Fix dealing with apps

### PR DESCRIPTION
**Pull request by VicDeo**
- [x] Fixes an empty `apps` directory in the checkpoint
- [x] Fixes 3rdparty apps removal on upgrade

### CODE REVIEW

**Comment by davitol** [comment]
Tested and WFM

**Comment by davitol** [comment]
We should backport this PR to stable10

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/updater/pull/470

**Comment by VicDeo** [comment]
[updater_10.0.3-10.0.8-patched.zip](https://github.com/owncloud/updater/files/1991797/updater_10.0.3-10.0.8-patched.zip)

**Pull request merged**
