### PR TITLE
Fix minification quirks. 

### LINKED ISSUE #184: Broken in C 8.2?
This screenshot will tell more:
untitled

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #184

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81

**Comment by PVince81** [comment]
So the minifier didn't like the previous code ?

:+1:

**Comment by PVince81** [comment]
second reviewer ? @nickvergessen @MorrisJobke

**Comment by MorrisJobke** [comment]
:+1:

**Comment by VicDeo** [comment]
@PVince81 in order to produce a working code after obfuscation angular needs explicit injection of parameters:
`function ($scope, $http) {`
should be declared as
`['$scope', '$http', function ($scope, $http) {`

Secondly, controller names should be literals as per 
`updaterApp.controller('updateCtrl', ['$scope', '$http', function ($scope, $http) {` and not 
`function updateCtrl ($scope, $http)`

I had a weird caching issue after changing the file so I just renamed it to fix this completely

**Comment by bcutter** [comment]
Worked :+1:

**Pull request merged**
